### ISSUE TITLE
Object.values(obj) not being compiled 

### ISSUE THREAD

**Issue by msongz** [Klustre/extender#1]
hi, I am very new with es6, why this code not work with extender?
```js
let salaries = {
  "John": 100,
  "Pete": 3100,
  "Mary": 2150
};
function topS (obj) {
  return Object.values(obj).sort((a,b) => b-a)[0];
}
alert(topS(salaries));
```

**Comment by Klustre** [comment]
Whenever something's not working have a look at the compiled code in the `build` folder and see if and how it's being transformed. If it's not transformed, it's probably not supported by `babel-preset-extendscript`. Check its [feature list](https://github.com/fusepilot/babel-preset-extendscript#features) to see what's supported. 

In this case you can use `Object.keys` with a `map`:
```js
let salaries = {
    "John": 100,
    "Pete": 3100,
    "Mary": 2150
  };
  function topS (obj) {
    return Object.keys(obj).map((key) => obj[key]).sort((a,b) => b-a)[0];
  }
alert(topS(salaries));
```
